django/conf/project_template/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

import app

admin.autodiscover()

urlpatterns = patterns('',
    (r'^app/', include(app.urls)),

    # Uncomment the admin/doc line below to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    )

django/db/models/base.py
import types
import sys
from itertools import izip

import django.db.models.manager     # Imported to register signal handler.
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned, FieldError, ValidationError, NON_FIELD_ERRORS
from django.core import validators
from django.db.models.fields import AutoField, FieldDoesNotExist
from django.db.models.fields.related import (OneToOneRel, ManyToOneRel,
    OneToOneField, add_lazy_relation)
from django.db.models.query import Q
from django.db.models.query_utils import DeferredAttribute
from django.db.models.deletion import Collector
from django.db.models.options import Options
from django.db import (connections, router, transaction, DatabaseError,
    DEFAULT_DB_ALIAS)
from django.db.models import signals
from django.db.models.loading import register_models, get_model
from django.utils.translation import ugettext_lazy as _
import django.utils.copycompat as copy
from django.utils.functional import curry, update_wrapper
from django.utils.encoding import smart_str, force_unicode
from django.utils.text import get_text_list, capfirst
from django.conf import settings

class ModelBase(type):
    """
    Metaclass for all models.
    """
    def __new__(cls, name, bases, attrs):
        super_new = super(ModelBase, cls).__new__
        parents = [b for b in bases if isinstance(b, ModelBase)]
        if not parents:
            # If this isn't a subclass of Model, don't do anything special.
            return super_new(cls, name, bases, attrs)

        # Create the class.
        module = attrs.pop('__module__')
        new_class = super_new(cls, name, bases, {'__module__': module})
        attr_meta = attrs.pop('Meta', None)
        abstract = getattr(attr_meta, 'abstract', False)
        if not attr_meta:
            meta = getattr(new_class, 'Meta', None)
        else:
            meta = attr_meta
        base_meta = getattr(new_class, '_meta', None)

        if getattr(meta, 'app_label', None) is None:
            # Figure out the app_label by looking one level up.
            # For 'django.contrib.sites.models', this would be 'sites'.
            model_module = sys.modules[new_class.__module__]
            kwargs = {"app_label": model_module.__name__.split('.')[-2]}
        else:
            kwargs = {}

        new_class.add_to_class('_meta', Options(meta, **kwargs))
        if not abstract:
            new_class.add_to_class('DoesNotExist', subclass_exception('DoesNotExist',
                    tuple(x.DoesNotExist
                            for x in parents if hasattr(x, '_meta') and not x._meta.abstract)
                                    or (ObjectDoesNotExist,), module))
            new_class.add_to_class('MultipleObjectsReturned', subclass_exception('MultipleObjectsReturned',
                    tuple(x.MultipleObjectsReturned
                            for x in parents if hasattr(x, '_meta') and not x._meta.abstract)
                                    or (MultipleObjectsReturned,), module))
            if base_meta and not base_meta.abstract:
                # Non-abstract child classes inherit some attributes from their
                # non-abstract parent (unless an ABC comes before it in the
                # method resolution order).
                if not hasattr(meta, 'ordering'):
                    new_class._meta.ordering = base_meta.ordering
                if not hasattr(meta, 'get_latest_by'):
                    new_class._meta.get_latest_by = base_meta.get_latest_by

        is_proxy = new_class._meta.proxy

        if getattr(new_class, '_default_manager', None):
            if not is_proxy:
                # Multi-table inheritance doesn't inherit default manager from
                # parents.
                new_class._default_manager = None
                new_class._base_manager = None
            else:
                # Proxy classes do inherit parent's default manager, if none is
                # set explicitly.
                new_class._default_manager = new_class._default_manager._copy_to_model(new_class)
                new_class._base_manager = new_class._base_manager._copy_to_model(new_class)

        # Bail out early if we have already created this class.
        m = get_model(new_class._meta.app_label, name, False)
        if m is not None:
            return m

        # Add all attributes to the class.
        for obj_name, obj in attrs.items():
            new_class.add_to_class(obj_name, obj)

        # All the fields of any type declared on this model
        new_fields = new_class._meta.local_fields + \
                     new_class._meta.local_many_to_many + \
                     new_class._meta.virtual_fields
        field_names = set([f.name for f in new_fields])

        # Basic setup for proxy models.
        if is_proxy:
            base = None
            for parent in [cls for cls in parents if hasattr(cls, '_meta')]:
                if parent._meta.abstract:
                    if parent._meta.fields:
                        raise TypeError("Abstract base class containing model fields not permitted for proxy model '%s'." % name)
                    else:
                        continue
                if base is not None:
                    raise TypeError("Proxy model '%s' has more than one non-abstract model base class." % name)
                else:
                    base = parent
            if base is None:
                    raise TypeError("Proxy model '%s' has no non-abstract model base class." % name)
            if (new_class._meta.local_fields or
                    new_class._meta.local_many_to_many):
                raise FieldError("Proxy model '%s' contains model fields." % name)
            while base._meta.proxy:
                base = base._meta.proxy_for_model
            new_class._meta.setup_proxy(base)

        # Do the appropriate setup for any model parents.
        o2o_map = dict([(f.rel.to, f) for f in new_class._meta.local_fields
                if isinstance(f, OneToOneField)])

        for base in parents:
            original_base = base
            if not hasattr(base, '_meta'):
                # Things without _meta aren't functional models, so they're
                # uninteresting parents.
                continue

            parent_fields = base._meta.local_fields + base._meta.local_many_to_many
            # Check for clashes between locally declared fields and those
            # on the base classes (we cannot handle shadowed fields at the
            # moment).
            for field in parent_fields:
                if field.name in field_names:
                    raise FieldError('Local field %r in class %r clashes '
                                     'with field of similar name from '
                                     'base class %r' %
                                        (field.name, name, base.__name__))
            if not base._meta.abstract:
                # Concrete classes...
                while base._meta.proxy:
                    # Skip over a proxy class to the "real" base it proxies.
                    base = base._meta.proxy_for_model
                if base in o2o_map:
                    field = o2o_map[base]
                elif not is_proxy:
                    attr_name = '%s_ptr' % base._meta.module_name
                    field = OneToOneField(base, name=attr_name,
                            auto_created=True, parent_link=True)
                    new_class.add_to_class(attr_name, field)
                else:
                    field = None
                new_class._meta.parents[base] = field
            else:
                # .. and abstract ones.
                for field in parent_fields:
                    new_class.add_to_class(field.name, copy.deepcopy(field))

                # Pass any non-abstract parent classes onto child.
                new_class._meta.parents.update(base._meta.parents)

            # Inherit managers from the abstract base classes.
            new_class.copy_managers(base._meta.abstract_managers)

            # Proxy models inherit the non-abstract managers from their base,
            # unless they have redefined any of them.
            if is_proxy:
                new_class.copy_managers(original_base._meta.concrete_managers)

            # Inherit virtual fields (like GenericForeignKey) from the parent
            # class
            for field in base._meta.virtual_fields:
                if base._meta.abstract and field.name in field_names:
                    raise FieldError('Local field %r in class %r clashes '\
                                     'with field of similar name from '\
                                     'abstract base class %r' % \
                                        (field.name, name, base.__name__))
                new_class.add_to_class(field.name, copy.deepcopy(field))

        if abstract:
            # Abstract base models can't be instantiated and don't appear in
            # the list of models for an app. We do the final setup for them a
            # little differently from normal models.
            attr_meta.abstract = False
            new_class.Meta = attr_meta
            return new_class

        new_class._prepare()
        register_models(new_class._meta.app_label, new_class)

        # Because of the way imports happen (recursively), we may or may not be
        # the first time this model tries to register with the framework. There
        # should only be one class for each model, so we always return the
        # registered version.
        return get_model(new_class._meta.app_label, name, False)

    def copy_managers(cls, base_managers):
        # This is in-place sorting of an Options attribute, but that's fine.
        base_managers.sort()
        for _, mgr_name, manager in base_managers:
            val = getattr(cls, mgr_name, None)
            if not val or val is manager:

app/views.py
from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from google.appengine.ext import db
from django import forms
from app.models import *
from django.template import RequestContext
import os, sys, datetime, copy, logging, settings, smtplib
from email.MIMEMultipart import MIMEMultipart
from email.MIMEImage import MIMEImage
from google.appengine.api import mail

class globvars():
  pages = [
      {'name':'Home', 'url':'../../'}, # add pages here
    ]
  proj_name = "Parents As Partners Image Drop" # change this!
  founders = [
    ]
  proj_description = "An image drop for the MAPP"
  context = {
      'pages': pages,
      'proj_name': proj_name,
      'founders': founders,
      'proj_description': proj_description,
      }

class UploadFileForm(forms.Form):
  photo1 = forms.FileField(required=False)
  photo2 = forms.FileField(required=False)
  photo3 = forms.FileField(required=False)

def send_app_email(receiver, subject, body, attachments=None):
  logging.warning("in send_app_email")
  logging.warning(attachments)
  if attachments:
    logging.warning('there are attachments')
    mail.send_mail(sender="MAPP Webmaster <mapp.webmaster@gmail.com>",
                   to=receiver,
                   subject=subject,
                   body=body,
                   attachments=attachments)
  else:
    mail.send_mail(sender="MAPP Webmaster <mapp.webmaster@gmail.com>",
                   to=receiver,
                   subject=subject,
                   body=body)
  return "sent"

def send_an_email(receiver, subject, body):
  s = smtplib.SMTP('smtp.gmail.com', 587)
  myGmail = 'intouch.registrator@gmail.com'
  myGMPasswd = 'iamarobot'
  s.ehlo()
  s.starttls()
  s.login(myGmail, myGMPasswd)
  msg = ("From: %s\r\nTo: %s\r\nSubject: %s\r\n\r\n%s" 
    %(myGmail, receiver, subject, body))
  s.sendmail(myGmail, [receiver], msg)
  s.quit()

def email_a_file(photo):
  logging.warning('in email_file')
  msg = "You have received a file from UploadToMail.appspot.com"
  subject = 'New File from UploadToMail'
  photoname = photo.name
  attachments = [(photoname, photo.read())]
##  msg = MIMEMultipart()
##  msg.attach(MIMEImage(photo.read()))
##  send_an_email('rattray.alex@gmail.com', 'sup, an image', msg)
  send_app_email(('mapp.webmaster@gmail.com','midatlantic_7ndu@sendtodropbox.com'), subject, msg, attachments)
  photo.close()
  return 1

def report_error(request):
  message = 'something failed!</h1><h3> The administrator has been notified, but you may reach him at rattray.alex@gmail.com if you like. \
    You may also send files to midatlantic_7ndu@sendtodropbox.com and mapp.webmaster@gmail.com instead of uploading them here. </h3>'
  send_app_email('rattray.alex@gmail.com','an error on upload to mail! ',str(request))
  return message
  
def index(request):
  if request.method == 'POST':
    logging.warning(request.FILES)
    logging.warning(request.POST)
    uploadform = UploadFileForm(data=request.POST, files=request.FILES)
    success = 0
    try:
      if uploadform.is_valid() and len(request.FILES) > 0:
        for photo in request.FILES:
          logging.warning('in for loop. '+ photo)
          send = email_a_file(request.FILES[photo])
          success += send
        message = str(success)+' files sent'
      else:
        message = report_error(request)
    except:
     message = report_error(request)
  else:
    uploadform = UploadFileForm()
    message = ''
  gv = globvars
  context = {
    'thispage':'Home',
    'uploadform':uploadform,
    'message':message,
      }
  context = dict(context, **gv.context) #combines the 'local' context with the 'global' context
  context_instance = RequestContext(request, context)
  return render_to_response('index.html', context_instance)

front-end/templates/about.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Home {% endblock %}

{% block nav %}
	{% for p in pages %}
		{% if p.name == thispage %}
			<li class="active"><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% else %}
			<li><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% endif %}
	{% endfor %}
{% endblock nav %}

{% block content %}
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
	<h1>About {{ proj_name }}</h1>
	<h2>A project primarily by Alex Rattray</h2>
	<hr>
  <p>
    Greg Terrono and I made 
    <a href="http://coursegrapher.com">CourseGrapher</a>
    during the 2011 Fall PennApps Hackathon, and took 
    second place. It was a lot of fun and a wild ride, 
    but I felt like some of what put us ahead of other 
    apps was our looks; not being a programmer by trade, 
    I had a bit more front-end experience than most. 
    I'd rather have teams win because they built something 
    impressive and useful than something beautiful; 
    style should be a level playing field. 
  </p>
  <p>
    We also spent way too much time scratching our heads
    about back-end stuff that should've been easy; 
    without enough time, we couldn't figure out how to 
    set up Django on App Engine (let alone set up an EC2 instance)
    and had to learn GAE's somewhat inferior webapp framework on the fly. 
  </p>
  <p>
    So, I decided to make this to make hackathons 
    (namely, the PennApps Spring 2012 Hackathon)
    more about writing logic and less about worry about styling, 
    server stuff, and other boilerplate. 
	</p>
  <p>
    Hopefully, you'll use this to just write an awesome app 
    without having to worry about writing a lot of CSS, 
    boring html, or worrying about setting up the initial django 
    project and setting up a server to host it online. 
  </p>
</div>
{% endblock content %}

front-end/templates/base.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!-- Consider adding an manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>{% block title %}{{ proj_name }}{% endblock %}</title>
  <meta name="description" content="{{ proj_description }}">
	<meta name="author" content="{% for author in founders %}{{ author.name }},{% endfor %}">

	<!-- Mobile viewport optimized: j.mp/bplateviewport -->
	<meta name="viewport" content="width=device-width,initial-scale=1">

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

	<!-- CSS: implied media=all -->
	<!-- CSS concatenated and minified via ant build script-->
	<link rel="stylesheet" href="front-end/media/css/h5bp-style.css">
	<link rel="stylesheet" href="front-end/media/css/bootstrap.min.css">
	<link rel="stylesheet" href="front-end/media/css/your-style.css"><!--put your css here. -->
	<link rel="stylesheet" href="front-end/media/css/h5bp-style-after.css">
	<!--NOTE: to write your own custom CSS, edit the file
		called "your-style.css", don't insert a <link> here. 
		your-style.css is in the proper place. 
		-->
	<!-- end CSS-->
    
	<!-- If you want to use LESS, 
		comment out the above bootstrap.min.js and your-style.css, 
		and uncomment the below. Also the LESS js script -->
	<!--<link rel="stylesheet/less" type="text/css" href="/front-end/media/bootstrap/lib/bootstrap.less">-->
	<!--<script src="/front-end/media/static/less-1.1.3.min.js"></script>-->

	<!-- All JavaScript at the bottom, except for Modernizr / Respond.
       Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
       For optimal performance, use a custom Modernizr build: www.modernizr.com/download/ -->
	<script src="front-end/media/static/modernizr-2.0.6.min.js"></script>

</head>

<body>
	<!-- html5 boilerplate told me to put <div id="container> there... 
		doubt it's necessary though. 
		Also, note that Bootstrap frequently uses "container"
		as a class, so avoid getting them mixed up. 
		-->
	<div id="container">

		<div id="main" role="main" class="container">
			{% block content %}
			{% endblock %}
      

			<footer style="text-align:center">
			{% block footer %}
				<p>&copy; {{ proj_name }} 2012</p>
        <p>
          A project by Alex Rattray for Keith Wilkerson of A Better Chance
        </p>
			{% endblock %}
			</footer>
		</div> <!--! end of #main.container-->
	</div> <!--! end of #container -->
  
    <!-- JavaScript at the bottom for fast page loading -->

	<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="front-end/media/static/jquery-1.6.2.min.js"><\/script>')</script>


	<!-- scripts concatenated and minified via ant build script-->
	<script defer src="front-end/media/static/h5bp-plugins.js"></script>
  <script src="front-end/media/bootstrap/js/bootstrap-twipsy.js"></script>
  <script src="front-end/media/bootstrap/js/bootstrap-popover.js"></script>
	<!--<script defer src="front-end/media/static/your-script.js"></script>-->
	<!-- more scripts here -->
  <script>
  var twoptions = {'html':true};
  $('footer p a').popover(twoptions);
  </script>
  {% block scripts %}
  {% endblock scripts %}
	<!-- end scripts-->

	<!-- Change UA-XXXXX-X to be your site's ID -->
	<script>
		window._gaq = [['_setAccount','UAXXXXXXXX1'],['_trackPageview'],['_trackPageLoadTime']];
		Modernizr.load({
		  load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
		});
	</script>
  



	<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
	   chromium.org/developers/how-tos/chrome-frame-getting-started -->
	<!--[if lt IE 7 ]>
		<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
		<script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->

</body>
</html>

front-end/templates/guestbook.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Home {% endblock %}

{% block nav %}
	{% for p in pages %}
		{% if p.name == thispage %}
			<li class="active"><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% else %}
			<li><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% endif %}
	{% endfor %}
{% endblock nav %}

{% block content %}
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
	<h1>Sample Guestbook App</h1>
	<h2>Browse the Backend to get a good feel for this stuff</h2>
	<hr>
	<p>
    Something
	</p>
</div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

front-end/templates/index.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | {{ thispage }} {% endblock %}

{% block content %}
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
	<h1>{{ proj_name }}</h1>
	<h2>{{ proj_description }}</h2>
  <hr>
  <h3>Each file must be less than 20MB and all three combined must be less than 30MB</h3>
  <form action="/" enctype="multipart/form-data" method="post">{% csrf_token %}
    <h3>Photo 1: <input type="file" name="photo1" id="id_photo1"></h3>
    <h3>Photo 2: <input type="file" name="photo2" id="id_photo1"></h3>
    <h3>Photo 3: <input type="file" name="photo3" id="id_photo1"></h3>
    <br>
    <input type="submit" class="btn primary large" name="Submit">
  </form>
  <h1 id="message">{{message|safe}}</h1>
</div>

{% endblock content %}

{% block scripts %}
<script type="text/javascript">
  $('input[type="submit"]').click(function(){
    $('#message').html('sending...');
  });
</script>
{% endblock scripts %}

front-end/templates/resources.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Home {% endblock %}

{% block nav %}
	{% for p in pages %}
		{% if p.name == thispage %}
			<li class="active"><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% else %}
			<li><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% endif %}
	{% endfor %}
{% endblock nav %}

{% block content %}
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
	<h1>Other great resources</h1>
	<hr>
	<p>
    Actually, why don't we just use the 
    <a href="../guestbook">Sample Guestbook App</a>
    for this? At least until I get my act together.
  </p>
</div>
{% endblock content %}

front-end/templates/signin.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Login {% endblock %}


{% block content %}
<div class="jtainer">
	<div class="frontcenter bigtext">Sign In</div><br />
	<form action="/signin/" method="post">{% csrf_token %}
	<fieldset>
        {% for field in form %}
			<div class="clearfix">
				{{ field.label_tag }}
				<div class="input">
					{{ field }}
				</div>
			</div>
		{% endfor %}
		<div class="clearfix">
			<div class="input">
				<input type="submit" value="Log In" class="btn large primary"/>
			</div>
		</div>
    </fieldset>
</form><div>
{% endblock content %}

front-end/templates/signup.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Sign Up {% endblock %}


{% block content %}
    <div class="jtainer">
		<div class="frontcenter bigtext">Sign on up!</div><br />
        <form action="/signup/" method="post" style="width:500px;">{% csrf_token %}
		<fieldset>
        {% for field in form %}
			<div class="clearfix">
				{{ field.label_tag }}
				<div class="input">
					{{ field }}
				</div>
			</div>
		{% endfor %}
		<div class="clearfix">
			<div class="input">
				<input type="submit" value="Sign Up" class="btn large primary"/>
			</div>
		</div
        </fieldset>
		</form>
    <div>
{% endblock content %}

front-end/templates/thanks.html
<div class="jtainer">
<div class="frontcenter">
<div class="bigtext"> Thanks for helping out {{ Project.creator }}!</div>

 <br />


    Soon, {{Project.creator}} will be able to thank you with more than just an exclamation mark. ($$$)
   <br />
   <br />

   
   Not registered for Decision Candy?
   <a href="../../signup/"> Sign Up </a>
	
	<br />
	<br />
	<br />
	<br />
<p>
	<a href="../../results/{{ Project.name }}"> 
	    <input id="Results" type="button" value="See Results for this Project" class="btn primary large"/>
	</a>

	<a href="../../../">
	    <input id="Projects" type="button" value="More Projects" class="btn large"/>
	</a>
</p>
<!--
	<a href="../../../">
	    <input id="RandProject" type="button" value="Random Project" class="btn large"/>
	</a>
-->
</p>

</div>
</div>
<br />

front-end/templates/tutorial.html
{% extends "base.html" %}

{% block title %}{{ block.super }} | Home {% endblock %}

{% block nav %}
	{% for p in pages %}
		{% if p.name == thispage %}
			<li class="active"><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% else %}
			<li><a href="{{ p.url }}">{{ p.name }}</a></li>
		{% endif %}
	{% endfor %}
{% endblock nav %}

{% block content %}
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">
	<h1>Get Started</h1>
	<h2><a href="#" class="popthis" rel="popover" title="A note:" data-placement="below"
    data-content="
      <p>
        This tutorial is written with the assumption that
        the reader may be a complete beginner in any given technology. 
      </p>
      <hr>
      <p>
        For example, when I did my first hackathon, 
        I didn't know what Git was or how to do anything
        in the command line. Other people might not have 
        ever touched django before, but be great with javascript. 
      </p>
      <hr>
      <p>
        So if it seems like I'm babying you, keep in mind:
        I know you're good/smart/experienced with 
        <em>something</em>, but not necessarily <em>everything</em>. 
      </p>
    ">
    This won't hurt a bit.</a>
  </h2>
	<hr>
	<ol>
    <h2>
      <li>
        Install Python 2.7
        <p>
          If you haven't already done this, though,
          you'll probably have trouble writing 
          Python logic. 
        </p>
        <p>
          Assuming you're mostly on the front-end team, 
          <a href="http://www.python.org/getit/releases/2.7/">go here</a>
          and do what it says. Note that if you're on a Mac, 
          you probably already have Python. 
          It may or may not be the correct version; 
          be sure to check. 
        </p>
      </li>
      <hr>
      <li>
        Install the Google App Engine SDK
        <p>
          No worries if you don't have experience with GAE. 
          Just hit up 
          <a href="http://code.google.com/appengine/downloads.html#Google_App_Engine_SDK_for_Python">
            this page
          </a>
          and do what it tells you.
        </p>
      </li>
      <hr>
      <li> Install Django
        <p>
          I'm actually not sure this is necessary. 
          I don't think it is. Let me double-check. 
        </p>
      </li>
      <hr>
      <li>
        Get Git (if not installed)
        <p>
          I'm serious. You need to do this. 
        </p>
        <p>
          Download and install Git <a href="http://git-scm.com/download">here</a>.
        </p>
        <p>
          Set up an account with either 
          <a href="https://github.com/signup/free">GitHub</a> 
          or <a href="https://bitbucket.org/account/signup/">BitBucket</a>. 
          GitHub's been "rocking git" for longer, 
          but BitBucket offers free unlimited *private* repositories, 
          with unlimited collaborators, if you have a .edu email address
          (aka if you go to college). 
        </p>
      </li>
      <hr>
      <li>
        Download this thing. 
        <p>
          Go <a href="https://bitbucket.org/rattray/hackpack-nodocs">here</a>
          and click "fork" in the upper right to fork the repository. 
          This will be your application, so give it the name you want, etc. 
          Now might also be a good time to add your teammates as collaborators, 
          but that could also be done later. 
        </p>
        <p>
          Once you're ready to move on, 
          open command prompt (or bash or whatever)
          and cd (change directory, for the unititated)
          to the <em>parent</em> directory of where you'd like to keep this. 
          For example, I have a 'djcode' folder where I keep all my code; 
          I would type <code>cd c:/djcode </code>. 
        </p>
        <p>
          Clone the repository you forked (aka, the one you just 'made')
          from bitbucket or git. This should be something like
          <code>git clone https://bitbucket.org/username/appname.git</code>. 
          You'll see the url towards the top of the repository page. 
        </p>
        <p>
          You can get the full thing with docs (basically what you're looking at)
          <a href="https://bitbucket.org/rattray/hackpack">here</a> 
          ('get source' or 'fork' in the upper right),
          but you should use
          it more for reference than as a template. 
          Especially if you're a beginner, 
          I would recommend taking a look at it anyway 
          as it was built expressly with reuse and 'teaching' 
          in mind. We'll get to this later. 
        </p>
      </li>
      <hr>
      <li>
        
      </li>
    </h2>
  </ol>
</div>
{% endblock content %}

{% block scripts %}
<script>
  var poptions = {'html':true};
  $('.popthis').popover(poptions);
</script>
{% endblock %}